#!/usr/bin/env bash

# This is the directory where your wallpapers are located.
WALLPAPER_DIR="/home/gerard/.config/assets/backgrounds/"

# Use find to list all image files, then pipe the list to tofi for selection
SELECTION=$(find "$WALLPAPER_DIR" -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" -o -name "*.gif" \) | sort | xargs -n 1 basename | tofi --prompt-text "Choose a wallpaper:" --width 800 --height 600)

# If a wallpaper was selected, save its path to a file.
if [ -n "$SELECTION" ]; then
    # Construct the full, absolute path to the selected wallpaper.
    WALLPAPER_PATH="$WALLPAPER_DIR$SELECTION"

    # Save the selected wallpaper's path to a file
    echo "$WALLPAPER_PATH" > ~/.config/hypr/last_wallpaper.txt
    
    # Kill any existing swaybg process
    pkill swaybg
    
    # Launch a new swaybg process with the new wallpaper
    swaybg -i "$WALLPAPER_PATH" & disown
fi